- name: Deploy SSH key
  hosts: all
  tasks:
    - name: test
      authorized_key:
        user: deploy
        state: present
        key: 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC3/J/pA8y5Z4a4a5A4a+... 114514@example.com'